### ISSUE TITLE
Doubts about the number of SNPs reported in two output files

### ISSUE THREAD

**Issue by EnzoAndree** [CFSAN-Biostatistics/snp-pipeline#10]
Hello.

I have installed the latest version of sap-pipeline on a ubuntu server, and I have a question about some results.

snp-pipeline reports:
208 SNPs within snpma. fasta (#nucleotides)
208 SNPs in snpma. vcf (#lines)
**134** SNPs in snpma_preserved.fasta (#nucleotides)
**208** SNPs in snpma_preserved.vcf (#lines)

I am a novice, but I expected an equal amount of SNP between the snpma_preserved.fasta and snpma_preserved.vcf files.

Is this difference normal?
Why does this difference exist?

Regards

I attach the following important files 
log.txt
metrics.tsv
snpma_preserved.fasta
snpma_preserved.vcf
snpma.fasta
snpma.vcf

[Archivo.zip](https://github.com/CFSAN-Biostatistics/snp-pipeline/files/1718394/Archivo.zip)

**Comment by stevendavis** [comment]
Thank you for your interest in the CFSAN snp pipeline.

Some of the snps in the snpma_preserved.vcf file do not pass the filters and are rejected, but the snp sites remain the in the file so you can see the reason why the snps did not pass the filters.  You can see the filter codes at the top of the VCF file. For example:

`
##FILTER=<ID=Region,Description="Position is in dense region of snps or near the end of the contig.">
`

You can grep for the rows containing snps that pass all the filters:

`$ grep -v "##"  snpma_preserved.vcf  | grep PASS | wc -l`
134

**Comment by EnzoAndree** [comment]
WOW! You're awesome!

Thank you so much for clarifying the numbers. I couldn't figure it out on my own.
