### ISSUE TITLE
CLASSPATH is not configured with the path to Picard

### ISSUE THREAD

**Issue by mshakya** [CFSAN-Biostatistics/snp-pipeline#11]
Hi.  I am trying to run the pipeline, but keep getting this error despite adding Picard to the path (CLASSPATH) as suggested. Please help.

I have fulfilled all dependencies, and surprisingly Varscan works which is in the same directory as the picard.

Here is what my CLASSPATH looks like:
```
echo $CLASSPATH
/opt/apps/picard-tools-1.80/picard.jar:/opt/apps/picard-tools-1.80/VarScan.v2.3.9.jar:/opt/apps/picard-tools-1.80/picard-1.80.jar:/opt/apps/picard-tools-1.80/VarScan.v2.3.9.jar:/opt/apps/picard-tools-1.80/picard-1.80.jar:/opt/apps/picard-tools-1.80/VarScan.v2.3.9.jar:/opt/apps/picard-tools-1.8
```

Thanks

**Comment by stevendavis** [comment]
@mshakya 
Some things to try:

Step 1:
Your CLASSPATH currently has Picard (and VarScan) listed multiple times.  
/opt/apps/picard-tools-1.80/picard.jar
/opt/apps/picard-tools-1.80/VarScan.v2.3.9.jar
/opt/apps/picard-tools-1.80/picard-1.80.jar
/opt/apps/picard-tools-1.80/VarScan.v2.3.9.jar
/opt/apps/picard-tools-1.80/picard-1.80.jar
/opt/apps/picard-tools-1.80/VarScan.v2.3.9.jar
/opt/apps/picard-tools-1.8

Configure the CLASSPATH with only one picard jar file.  

Step 2:
Type this command at your command line:
`java picard.cmdline.PicardCommandLine`
This should not produce an error.

Step 3:
If you still see errors, you could try a newer version of Picard.

**Comment by mshakya** [comment]
Thank you @stevendavis . I was using the older version, but i upgraded  and now it works. however, i ran into another separate problem. I will open a separate issue for that. Thanks again.
