### ISSUE TITLE
New release of picard

### ISSUE THREAD

**Issue by EnzoAndree** [CFSAN-Biostatistics/snp-pipeline#13]
Hello,

I would like to point out that with the new picard (2.18.10) snp-pipeline raises an error: 

> CLASSPATH is not configured with the path to Picard

Although the CLASSPATH is well configured, beacuse just installing the previous version (2.18.9) everything goes smoothly.

It is not a big deal but the error message is't very informative.

Greetings

**Comment by stevendavis** [comment]
This is fixed in the new version 2.0.0 released today.

**Comment by bifidoman** [comment]
Hi


I installed snp_pipeline and picard today and I get the same error

**Comment by bifidoman** [comment]
Hi

I even get this error when installing Picard 2.18.9 and when changing the .conf file to "removeduplicatereads=False"
any help is appreciated

**Comment by stevendavis** [comment]
@bifidoman Please reach out to me directly.  You can find my email address in my github profile.  Send me the full path to your picard.jar file and send me the contents of your CLASSPATH environment variable.  echo $CLASSPATH

Meanwhile, there is a workaround.  With the release of cfsan snp pipeline version 2.0.0, Picard is used in two parts of the workflow, removing duplicate reads and during local realignment around indels.  As a workaround, you could disable both of these steps in the configuration file.

RemoveDuplicateReads=false
EnableLocalRealignment=false

**Comment by stevendavis** [comment]
Fixed in release 2.0.1 today.  My apologies for the delay.
