### ISSUE TITLE
Pseudo-whole genome alignment from the pipeline?

### ISSUE THREAD

**Issue by cizydorczyk** [CFSAN-Biostatistics/snp-pipeline#14]
Hello,

Is it possible to obtain a pseudo-whole genome alignment from the pipeline? That is, an alignment that includes invariant sites from the reference for each isolate, with missing positions masked? From my understanding, the "snplist.txt" output file contains a list of all SNP positions -- does this include ALL positions a SNP occurs at, including positions absent in one isolate but present in another (i.e. not only core SNPs)?

Or are there any plans on implementing such a feature, to allow for the running of recombination-masking tools after running the SNP calling pipeline?

Thank you,
Conrad

**Comment by stevendavis** [comment]
It's not clear to me what you are requesting. The pipeline calls snps in each isolate and generates a snp matrix as well as a vcf file:
snpma_preserved.fasta
snpma_preserved.vcf

The pipeline is capable of calling snps in isolates regardless of whether the snp position is present in other isolates.  Missing read coverage in one isolate does not preclude calling snps in that region in other isolates.

There are no new features planned at this time.
