### ISSUE TITLE
how to set up input files if I have both Illumina and nanopore long reads for dozens bacterial genomes

### ISSUE THREAD

**Issue by limin321** [CFSAN-Biostatistics/snp-pipeline#17]
Hi 

I have bacterial genome which is hybrid assembled with both short and long reads. The assembly quality is pretty high.  Now I want to call SNPs for association analysis, can I use my hybrid assembly as input for SNPs calling, or only fastq data. However, I have both long and short reads for each strain.  
SNPs caller for bacteria like CFSAN, NASP, SNIPPY, PHEnix etc all take fastq data. Why none of them take assembled fasta data? 

Thanks,

**Comment by stevendavis** [comment]
The cfsan snp pipeline takes short-read fastq input.  You could try ParSnp.
