### ISSUE TITLE
samtools version check

### ISSUE THREAD

**Issue by rlpires** [CFSAN-Biostatistics/snp-pipeline#19]
The minimal version requirement for samtools fails if for example the user deploys samtools version 1.10. This is because as a number 1.10 is smaller than the minimal version, 1.4.
A fix is straightforward.
What is the protocol, should I submit a pull request?

Greets,
-- RP

**Comment by stevendavis** [comment]
Sure, you may submit a pull request.  You may also add yourself to AUTHORS.rst if you would like to do so.  You will be our first external contributor.

**Comment by rlpires** [comment]
> Sure, you may submit a pull request. You may also add yourself to AUTHORS.rst if you would like to do so. You will be our first external contributor.

OK, I shall start a pull request. According to your flow, to which branch should it go?
Adding myself to the AUTHORS file with such a minimal change will give me an impostor syndrome feeling!

**Comment by stevendavis** [comment]
Please make the change in the 2.2-branch. I will propagate the changes to master and release the next version.
There are samtools versions checks in run.py and map_reads.py.

**Comment by stevendavis** [comment]
Fixed in version 2.2.1.  I had to fix something else and just went ahead and fixed this also.
