### ISSUE TITLE
Picard does't work on java 1.8, GATK 3.8 dose't not work on java 20

### ISSUE THREAD

**Issue by jinyanjane** [CFSAN-Biostatistics/snp-pipeline#27]
In my CFSAN SNP pipeline, Picard does't work on java 1.8, GATK 3.8 dose't not work on java 20. 
I don't know how to set the two software in diferent java version.

**Comment by crashfrog** [comment]
We usually pin to Picard 2.27.5 (the most recent Java 8-supporting version)
for this reason. We're pinned to GATK 3.8 and can't update (GATK 4 dropped
support for a component we call) so unfortunately you'll need to downgrade
Picard to 2.27.5.

Justin

**Comment by jinyanjane** [comment]
Hi Justin,
Okay, I get it. But I didn't find Picard 2.27.5 package n the Internet. Would you kindly share me the the download link with me？

Jane

**Comment by jinyanjane** [comment]
Hi Justin,
I have got Picard 2.27.5 package and run pipeline successfully. Thank you very much for you kindly support. 

BR
Jane

**Comment by crashfrog** [comment]
Glad to hear it! We're hoping future versions of the pipeline are a little
easier to install.
