### ISSUE TITLE
pipeline halted at mergeVcf.sh

### ISSUE THREAD

**Issue by rodsa** [CFSAN-Biostatistics/snp-pipeline#4]
I am using this pipeline for the first time on Ubuntu. Everything ran smoothly until the merge command started. 

# Command           : /usr/local/bin/mergeVcf.sh snp-pipeline-test//sampleDirectories.txt.filtered
# Working Directory : /home/manager/Desktop
# Hostname          : wtsi-vm
# RAM               : 30,211 MB

# 2016-04-12 14:43:07 Starting merge operations
Copying snp-pipeline-test//samples/72/consensus.vcf to tmp.vcf.BqcQnUy7/72.vcf
Copying snp-pipeline-test//samples/52/consensus.vcf to tmp.vcf.BqcQnUy7/52.vcf
Copying snp-pipeline-test//samples/5/consensus.vcf to tmp.vcf.BqcQnUy7/5.vcf
Compressing tmp.vcf.BqcQnUy7/52.vcf
Compressing tmp.vcf.BqcQnUy7/5.vcf
Compressing tmp.vcf.BqcQnUy7/72.vcf
Indexing tmp.vcf.BqcQnUy7/52.vcf.gz
Indexing tmp.vcf.BqcQnUy7/5.vcf.gz
Indexing tmp.vcf.BqcQnUy7/72.vcf.gz
[main] Unrecognized command.

What could be the reason of this failure? The tmp directory contains vcf files and compressed, indexed vcf files.

**Comment by stevendavis** [comment]
The snp-pipeline uses bcftools to merge the individual sample vcf files together into a multi-vcf file.  I'm guessing you have an old version of bcftools installed.  Type this at the command line:

$ bcftools --help

If you need to install it, I recommend version 1.1.  This is how I did the install on my workstation:

Download from http://sourceforge.net/projects/samtools/files/samtools/1.1/
cd  ~/software
tar -jxf  ~/Downloads/bcftools-1.1.tar.bz2
cd bcftools-1.1
make
Edit .bashrc, add this:
	export PATH=$PATH:~/software/bcftools-1.1

Let us know how that works out for you.

**Comment by rodsa** [comment]
Thanks! 
I updated my bcftools but now I see an error with SAMtools 1.3 at a much
earlier step, during the mapping. Gotta go now, but will mail you tomorrow
with more details.
Does the pipeline run on OSX? I saw an issue with mktemp.
Best, 
César 

From:  Steve Davis <notifications@github.com>
Reply-To:  CFSAN-Biostatistics/snp-pipeline
<reply+006bed5b4c107d1beac89c2853e788160f22a74a439fe45492cf000000011325284f9
2a169ce08d05275@reply.github.com>
Date:  martes, 12 de abril de 2016, 3:19 p.m.
To:  CFSAN-Biostatistics/snp-pipeline <snp-pipeline@noreply.github.com>
Cc:  Cesar Rodriguez <cesar.rodriguezsanchez@ucr.ac.cr>
Subject:  Re: [CFSAN-Biostatistics/snp-pipeline] pipeline halted at
mergeVcf.sh (#4)


The snp-pipeline uses bcftools to merge the individual sample vcf files
together into a multi-vcf file.  I'm guessing you have an old version of
bcftools installed.  Type this at the command line:

$ bcftools --help

If you need to install it, I recommend version 1.1.  This is how I did the
install on my workstation:

Download from http://sourceforge.net/projects/samtools/files/samtools/1.1/
cd  ~/software
tar -jxf  ~/Downloads/bcftools-1.1.tar.bz2
cd bcftools-1.1
make
Edit .bashrc, add this:
 export PATH=$PATH:~/software/bcftools-1.1

Let us know how that works out for you.


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/CFSAN-Biostatistics/snp-pipeline/issues/4#issuecomment-2
09107256>

**Comment by rodsa** [comment]
Dear Steve, 
I had to play around with my samtools, bcftools and pyvcf versions to get
the pipeline working, but I finally managed to.
It is a great tool and I am enjoying testing it.
Thanks a lot for developing it.
César

From:  Steve Davis <notifications@github.com>
Reply-To:  CFSAN-Biostatistics/snp-pipeline
<reply+006bed5b4c107d1beac89c2853e788160f22a74a439fe45492cf000000011325284f9
2a169ce08d05275@reply.github.com>
Date:  martes, 12 de abril de 2016, 3:19 p.m.
To:  CFSAN-Biostatistics/snp-pipeline <snp-pipeline@noreply.github.com>
Cc:  Cesar Rodriguez <cesar.rodriguezsanchez@ucr.ac.cr>
Subject:  Re: [CFSAN-Biostatistics/snp-pipeline] pipeline halted at
mergeVcf.sh (#4)


The snp-pipeline uses bcftools to merge the individual sample vcf files
together into a multi-vcf file.  I'm guessing you have an old version of
bcftools installed.  Type this at the command line:

$ bcftools --help

If you need to install it, I recommend version 1.1.  This is how I did the
install on my workstation:

Download from http://sourceforge.net/projects/samtools/files/samtools/1.1/
cd  ~/software
tar -jxf  ~/Downloads/bcftools-1.1.tar.bz2
cd bcftools-1.1
make
Edit .bashrc, add this:
 export PATH=$PATH:~/software/bcftools-1.1

Let us know how that works out for you.


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/CFSAN-Biostatistics/snp-pipeline/issues/4#issuecomment-2
09107256>

**Comment by stevendavis** [comment]
Fixed in release 0.6.1 -- added support for SAMtools 1.3.
