### ISSUE TITLE
SAMtools V.1.3.1 error with prep samples

### ISSUE THREAD

**Issue by mstasiewicz** [CFSAN-Biostatistics/snp-pipeline#5]
I just ran the pipeline OK with the lambda virus test data, but the had an error on my own data.  SAMtools wouldn't sort the .bam file when I was using SAMtools v1.3.1.  
I corrected this by adding the '-o' flag for the output directory in the prepSamples.sh scrip around line 190.

**Comment by stevendavis** [comment]
Fixed in release 0.6.1 -- added support for SAMtools 1.3.

**Comment by mstasiewicz** [comment]
Great.  Now I have to figure out how to update (in case I missed that).
I'm really new to maintaining a UNIX system.  - Matt

---

Matthew Stasiewicz.

Assistant Professor, Dept. of Food Science & Human Nutrition

University of Illinois at Urbana-Champaign

Graduate, Food Science Department. Cornell University

mstasie@illinois.edu

(313) 212-7486

**Comment by hughrandFDA** [comment]
Hi Matt,

  We can help if you get stuck. Just holler.

Hugh Rand
Supervisor, Analytics Team, Biostatistics Branch
Office of Analytics and Outreach
FDA Center for Food Safety and Applied Nutrition
5100 Paint Branch Pkwy
College Park, MD 20740
Office: 240-402-1846
