### ISSUE TITLE
running call_sites on indexed bam file

### ISSUE THREAD

**Issue by cb4github** [CFSAN-Biostatistics/snp-pipeline#7]
Dear Folks,

I already have said .bam file and accompanying .bai file.

Is it possible (perhaps in the near future) to configure call_sites to accept said bam file vice the expected, default ...reads.sam file.

Thanks for all your efforts.

Best,
Carl B.

**Comment by stevendavis** [comment]
In the new snp-pipeline release version 2.0.0, the functionality is rearranged.  The map_reads step produces a finished BAM file and the call_sites step processes the BAM file to find sites with likely snps.

See the process diagram here: https://snp-pipeline.readthedocs.io/en/latest/dataflow.html
See the command reference here: https://snp-pipeline.readthedocs.io/en/latest/cmd_ref.html#call-sites
