### ISSUE TITLE
UnboundLocalError in distance.py:calculate_snp_distances

### ISSUE THREAD

**Issue by crashfrog** [CFSAN-Biostatistics/snp-pipeline#9]
Line 73:

```
        #------------------------------
        # Read in snp matrix file
        #------------------------------
        seqs = {}
        with open(input_file) as ifile:
            for line in ifile:
                line = line.rstrip('\n')
                if line.startswith('>'):
                    curr_sample = line.lstrip('>')
                    seqs[curr_sample] = ''
                else:
                    seqs[curr_sample] += str(line)
```

In this code, if the line does not start with ```>```, the symbol ```curr_sample``` is never defined, but is referenced. That'll throw UnboundLocalError.

**Comment by stevendavis** [comment]
@crashfrog The code assumes each sequence in the input fasta starts with '>'.  In particular, it assumes the first line in the file will start with '>'.  Can you share the input fasta file created by the pipeline where this assumption is not true?
